startCommand: |
  bash -lc '
    python manage.py migrate --noinput &&
    python manage.py createsuperuser --noinput || true &&
    gunicorn movie_theater_booking.wsgi:application --bind 0.0.0.0:$PORT
  '
envVars:
  - key: DJANGO_SUPERUSER_USERNAME
    value: admin
  - key: DJANGO_SUPERUSER_EMAIL
    value: admin@example.com
  - key: DJANGO_SUPERUSER_PASSWORD
    value: Django_Pass_2025

